# Generated by Django 4.2.4 on 2023-08-10 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_populate_notification_types_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="bio",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="reposts",
        ),
        migrations.AddField(
            model_name="tweet",
            name="like",
            field=models.ManyToManyField(related_name="tweets_likes", through="core.Like", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="tweet",
            name="repost",
            field=models.ManyToManyField(
                related_name="tweets_reposts", through="core.Repost", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="tweet",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="core.tweet"),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tweet_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to="core.notificationtype"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="repost",
            name="tweet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reposts", to="core.tweet"
            ),
        ),
        migrations.AlterField(
            model_name="repost",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tweet_reposts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="reply_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tweets_replies", to="core.tweet"
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="tags",
            field=models.ManyToManyField(db_table="tweet_tags", related_name="tweets", to="core.tag"),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tweets", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="users", to="core.country"
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
