# Generated by Django 4.2.4 on 2023-08-15 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_user_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="reply_to",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="tweets_replies", to="core.tweet"
            ),
        ),
    ]
