# Generated by Django 4.2.4 on 2023-08-28 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_tweet_reply_counter_remove_user_followers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ManyToManyField(related_name="notifications", to=settings.AUTH_USER_MODEL),
        ),
    ]
