# Generated by Django 4.2.4 on 2023-08-28 19:48

import core.models.user
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_notification_user_notification_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tweets_replies",
                to="core.tweet",
            ),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="tags",
            field=models.ManyToManyField(blank=True, db_table="tweet_tags", related_name="tweets", to="core.tag"),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="core.country",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                blank=True, db_table="followers", related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user.user_photo_directory_path),
        ),
    ]
