# Generated by Django 4.2.4 on 2023-08-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_tweet_reply_to_alter_tweet_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True),
        ),
    ]
