# Generated by Django 4.2.4 on 2023-08-29 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_user_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ManyToManyField(
                db_table="notifications_users", related_name="notifications", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
